### ISSUE TITLE
GetExtraType ContainerChanges may need a null check

### ISSUE THREAD

**Issue by lStewieAl** [carxt/JohnnyGuitarNVSE#10]
https://github.com/carxt/JohnnyGuitarNVSE/blob/15c93d3b00c5a0e0632bb3aec27671ef6a6a43ba/JG/JohnnyGuitar/JohnnyGuitarNVSE.h#L345

See https://github.com/jazzisparis/JIP-LN-NVSE/blob/019a8ab87074d05837095ab19cf25bdc434efe94/functions_ln/ln_fn_inventory.h#L38

**Comment by c6-dev** [comment]
Added null checks in 3.80, although the crash some users were having was in GetExtraType itself
