### ISSUE TITLE
BaseExtraList::GetByType should be thread safe

### ISSUE THREAD

**Issue by lStewieAl** [carxt/JohnnyGuitarNVSE#9]
https://github.com/carxt/JohnnyGuitarNVSE/blob/15c93d3b00c5a0e0632bb3aec27671ef6a6a43ba/nvse/nvse/GameBSExtraData.cpp#L12

The function in the game has a light critical section, should add one similar to how JIP did here - https://github.com/jazzisparis/JIP-LN-NVSE/blob/019a8ab87074d05837095ab19cf25bdc434efe94/nvse/GameBSExtraData.cpp#L16

**Comment by c6-dev** [comment]
Done in 3.80
